version: '3'

services:

  mysql:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 33060:3306
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
    command: mysqld --skip-grant-tables --skip-networking
    tty: true

  php-apache:
    build: ./docker/php-apache
    volumes:
      - ./htdocs:/var/www/html
      - ./php/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - VIRTUAL_HOST=mydevelop-env.localhost

